pipeline:
  identifier: Build_jhttp_1731430434436
  name: Build jhttp
  orgIdentifier: TPMLabs
  projectIdentifier: testal
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: test_al
        repoName: jhttp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: run install
                  spec:
                    shell: Sh
                    command: mvn clean install -DskipTests
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: mvn install
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    caching: true
                    connectorRef: <+input>
                    repo: hello/world
                    tags:
                      - latest
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
